version: "2.1"
services:

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks: 
      - nextcloud_network
    volumes: 
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment: 
      - MYSQL_ROOT_PASSWORD={ROOT PASSWORD HERE}
      - MYSQL_PASSWORD={PASSWORD HERE}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  nextcloud:
      image: lscr.io/linuxserver/nextcloud:latest
      container_name: nextcloud
      hostname: {HOSTNAME HERE}
      networks: 
        - nextcloud_network
      depends_on: 
        - db
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Vancouver
      volumes:
        - ./app/config:/config
        - ./data:/data
      ports:
        - 443:443
      restart: unless-stopped

volumes: 
  nextcloud: 
  db: 

networks: 
  nextcloud_network:

